title: GDG Pisa
description: "Il Google Developer Group di Pisa è una community dove le persone possono condividere liberamente le proprie idee, le proprie conoscenze ed esperienze in campo tecnologico.
Non è richiesta alcuna competenza particolare, se sei semplicemente interessato alla tecnologia non ti resta che entrare in contatto con noi :D"
author: GDG Pisa
logo: /static/img/logo-adesivo.png
github: https://github.com/gdgpisa
about: Google Developer Group Pisa

baseurl: ""
url: "https://gdgpisa.it"

allowsearch: true

# disqus_shortname: aboutashu
google_analytics: UA-109677042-1

share:
  twitter_username: \gdgpisa
  fb_appid: 000000000000


enableTags: true
tagarray: []
paginate: 20
per_page: 20
paginate_path: "/blog/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist, jekyll-redirect-from]
